version: '2'
services:
    db:
        image: postgres
        container_name: postgres
        volumes:
            - /tmp/postgres/data/:/var/lib/postgres/
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"
        networks:
            - collager-network
    web:
        image: collager.v1
        container_name: collager
        depends_on:
        - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_FLYWAY_USER=postgres
            - SPRING_FLYWAY_PASSWORD=postgres
            - SPRING_FLYWAY_SCHEMAS=public
            - GCP_BUCKET_NAME=
            - GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp_creds.json
            - IMAGGA_API_ENDPOINT=https://api.imagga.com/v2
            - IMAGGA_KEY=
            - IMAGGA_secret=
            - SERVER_PORT=8080
        ports:
            - '8080:8080'
        networks:
            - collager-network
networks:
    collager-network: